---

name: Code Testing
on:
  push
#  pull-request:
#    types: [opened, reopened]

jobs:
  pylint:
    name: Run pylint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: |
          echo $PWD
          echo $GITHUB_WORKSPACE
          pylint $GITHUB_WORKSPACE/j2lint
